Avoids calling completion twice on failure
contentful/contentful.swift pull request #363
Opened 2022-05-12 14:25 UTC by tristan-warner-smith

Swift's concurrency Task API will crash if completion handlers are called more than once in continuations.
This is a critical issue affecting the Contentful SDK and this PR patches one case of it happening.

I encountered this because I've wrapped `fetchArray(of` in a `Task` and this triggers:
`Fatal error: SWIFT TASK CONTINUATION MISUSE: fetchArray(of:) tried to resume its continuation more than once, throwing Unknown error occured during decoding.!`
In my case I was mistakenly decoding a value using `decode` rather than `decodeIfPresent`.

Here's the client code to repro (if you decode erroneously as described above).

```swift
func fetchArray<ResourceType: EntryDecodable & FieldKeysQueryable>(of resourceType: ResourceType.Type) async throws -> [ResourceType] {
        
        try await withCheckedThrowingContinuation { continuation in
            fetchArray(of: resourceType) { result in
                switch result {
                case .success(let results):
                    continuation.resume(returning: results.items.map { $0 as ResourceType })
                case .failure(let error):
                    continuation.resume(throwing: error)
                }
            }
        }
    }
```

Client.swift:476 and 500 in Contentful 5.5.2.

2022-05-12 14:27 UTC, tristan-reveri commented
The suggested approach of tracking it with a simple boolean isn't elegant but it's effective.
As I understand it you always want to call `churnLinks` after an attempted decode even if it fails, I'm not sure if that's still a valid state but if it is then potentially wrapping the `churnLinks` code into a `defer {}` will allow you to remove the second decode attempt.

2022-05-19 21:42 UTC, mariuskatcontentful requested changes
Hey, this is now out of date with the master. Could you merge master again into your branch and i will review it

2022-05-23 12:21 UTC, tristan-reveri commented
Updated as requested @mariuskatcontentful.

2022-06-07 20:29 UTC, mariuskatcontentful requested changes
Could you just make the code return after the line 476 then there would not be need for any flags setting and checking later

2022-06-07 20:58 UTC, tristan-reveri commented
You could, but I read via other issues and PR attempts that the authors wanted to execute the linkResolver code path regardless of the parsers failing.

2022-06-09 10:06 UTC, mariuskatcontentful commented
> Updated as requested @mariuskatcontentful.

@tristan-reveri I do not think there is need to call churnLinks if the JSON parsin failed as links would have been already churned for each succeeded json before and if current JSON fails - there either would not be any links to churn or there would be the same "unchurnable" links that would not be able to resolve yet still. Any reasons why you would want that apart from my mentioned ones?

2022-06-09 11:18 UTC, mariuskatcontentful commented
@tristan-reveri ok in that case i think if you could just adjust your PR to return just after the first error completion i will approve it immediately :)

2022-06-12 17:44 UTC, mariuskatcontentful approved these changes

2022-06-18 13:32 UTC, closed without merging